// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	login: {
		form: {
			/**
			 * L​o​g​i​n​ ​w​i​t​h​ ​G​i​t​h​u​b
			 */
			socialLoginGithub: string
			/**
			 * L​o​g​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
			 */
			socialLoginGoogle: string
			/**
			 * L​o​g​i​n​ ​w​i​t​h​ ​T​w​i​t​t​e​r
			 */
			socialLoginTwitter: string
			/**
			 * L​o​g​i​n​ ​t​o​ ​y​o​u​r​ ​a​c​c​o​u​n​t
			 */
			title: string
			/**
			 * D​o​n​t​ ​h​a​v​e​ ​a​c​c​o​u​n​t​?
			 */
			registerLabel: string
			/**
			 * S​i​g​n​ ​u​p​ ​h​e​r​e
			 */
			registerLink: string
			/**
			 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
			 */
			forgotPasswordLabel: string
			/**
			 * E​m​a​i​l
			 */
			emailLabel: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l
			 */
			emailPlaceholder: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			passwordLabel: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
			 */
			passwordPlaceholder: string
			/**
			 * L​o​g​i​n
			 */
			submitButton: string
			/**
			 * o​r
			 */
			seperatorLabel: string
			/**
			 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l
			 */
			emailRequired: string
			/**
			 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l
			 */
			emailValid: string
			/**
			 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
			 */
			passwordRequired: string
			/**
			 * I​n​v​a​l​i​d​ ​L​o​g​i​n
			 */
			loginError: string
			/**
			 * E​m​a​i​l​ ​n​o​t​ ​v​e​r​i​f​i​e​d
			 */
			emailNotVerified: string
			/**
			 * C​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​r​e​s​e​n​d​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l
			 */
			emailNotVerifiedLink: string
			/**
			 * E​m​a​i​l​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​v​e​r​i​f​i​e​d​,​ ​y​o​u​ ​m​a​y​ ​n​o​w​ ​l​o​g​i​n
			 */
			emailVerified: string
		}
	}
	register: {
		form: {
			/**
			 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​a​c​c​o​u​n​t
			 */
			title: string
			/**
			 * A​l​r​e​a​d​y​ ​r​e​g​i​s​t​e​r​e​d​?
			 */
			loginLabel: string
			/**
			 * L​o​g​ ​i​n​ ​h​e​r​e
			 */
			loginLink: string
			/**
			 * E​m​a​i​l
			 */
			emailLabel: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l
			 */
			emailPlaceholder: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			passwordLabel: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
			 */
			passwordPlaceholder: string
			/**
			 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
			 */
			passwordConfirmLabel: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​a​g​a​i​n
			 */
			passwordConfirmPlaceholder: string
			/**
			 * R​e​g​i​s​t​e​r
			 */
			submitButton: string
			/**
			 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l
			 */
			emailRequired: string
			/**
			 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l
			 */
			emailValid: string
			/**
			 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
			 */
			passwordRequired: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​{​m​i​n​}​ ​c​h​a​r​a​c​t​e​r​s
			 * @param {number} min
			 */
			passwordMinError: RequiredParams<'min'>
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​m​o​s​t​ ​{​m​a​x​}​ ​c​h​a​r​a​c​t​e​r​s
			 * @param {number} max
			 */
			passwordMaxError: RequiredParams<'max'>
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r
			 */
			passwordLowerCaseError: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​u​p​p​e​r​c​a​s​e​ ​l​e​t​t​e​r
			 */
			passwordUppercaseCaseError: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​n​u​m​b​e​r
			 */
			passwordNumberError: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r
			 */
			passwordSpecialError: string
			/**
			 * P​l​e​a​s​e​ ​c​o​n​f​i​r​m​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
			 */
			confirmPasswordRequired: string
			/**
			 * P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h
			 */
			confirmPasswordError: string
			/**
			 * Y​o​u​ ​h​a​v​e​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​r​e​g​i​s​t​e​r​e​d​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​c​o​n​f​i​r​m​ ​y​o​u​r​ ​a​c​c​o​u​n​t​.
			 */
			success: string
			/**
			 * C​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​r​e​t​u​r​n​ ​t​o​ ​t​h​e​ ​l​o​g​i​n​ ​p​a​g​e
			 */
			successReturn: string
		}
	}
}

export type TranslationFunctions = {
	login: {
		form: {
			/**
			 * Login with Github
			 */
			socialLoginGithub: () => LocalizedString
			/**
			 * Login with Google
			 */
			socialLoginGoogle: () => LocalizedString
			/**
			 * Login with Twitter
			 */
			socialLoginTwitter: () => LocalizedString
			/**
			 * Login to your account
			 */
			title: () => LocalizedString
			/**
			 * Dont have account?
			 */
			registerLabel: () => LocalizedString
			/**
			 * Sign up here
			 */
			registerLink: () => LocalizedString
			/**
			 * Forgot password?
			 */
			forgotPasswordLabel: () => LocalizedString
			/**
			 * Email
			 */
			emailLabel: () => LocalizedString
			/**
			 * Enter your email
			 */
			emailPlaceholder: () => LocalizedString
			/**
			 * Password
			 */
			passwordLabel: () => LocalizedString
			/**
			 * Enter your password
			 */
			passwordPlaceholder: () => LocalizedString
			/**
			 * Login
			 */
			submitButton: () => LocalizedString
			/**
			 * or
			 */
			seperatorLabel: () => LocalizedString
			/**
			 * Please enter your email
			 */
			emailRequired: () => LocalizedString
			/**
			 * Please enter a valid email
			 */
			emailValid: () => LocalizedString
			/**
			 * Please enter your password
			 */
			passwordRequired: () => LocalizedString
			/**
			 * Invalid Login
			 */
			loginError: () => LocalizedString
			/**
			 * Email not verified
			 */
			emailNotVerified: () => LocalizedString
			/**
			 * Click here to resend verification email
			 */
			emailNotVerifiedLink: () => LocalizedString
			/**
			 * Email successfully verified, you may now login
			 */
			emailVerified: () => LocalizedString
		}
	}
	register: {
		form: {
			/**
			 * Create a new account
			 */
			title: () => LocalizedString
			/**
			 * Already registered?
			 */
			loginLabel: () => LocalizedString
			/**
			 * Log in here
			 */
			loginLink: () => LocalizedString
			/**
			 * Email
			 */
			emailLabel: () => LocalizedString
			/**
			 * Enter your email
			 */
			emailPlaceholder: () => LocalizedString
			/**
			 * Password
			 */
			passwordLabel: () => LocalizedString
			/**
			 * Enter your password
			 */
			passwordPlaceholder: () => LocalizedString
			/**
			 * Confirm Password
			 */
			passwordConfirmLabel: () => LocalizedString
			/**
			 * Enter your password again
			 */
			passwordConfirmPlaceholder: () => LocalizedString
			/**
			 * Register
			 */
			submitButton: () => LocalizedString
			/**
			 * Please enter your email
			 */
			emailRequired: () => LocalizedString
			/**
			 * Please enter a valid email
			 */
			emailValid: () => LocalizedString
			/**
			 * Please enter your password
			 */
			passwordRequired: () => LocalizedString
			/**
			 * Password must be at least {min} characters
			 */
			passwordMinError: (arg: { min: number }) => LocalizedString
			/**
			 * Password must be at most {max} characters
			 */
			passwordMaxError: (arg: { max: number }) => LocalizedString
			/**
			 * Password must contain at least one lowercase letter
			 */
			passwordLowerCaseError: () => LocalizedString
			/**
			 * Password must contain at least one uppercase letter
			 */
			passwordUppercaseCaseError: () => LocalizedString
			/**
			 * Password must contain at least one number
			 */
			passwordNumberError: () => LocalizedString
			/**
			 * Password must contain at least one special character
			 */
			passwordSpecialError: () => LocalizedString
			/**
			 * Please confirm your password
			 */
			confirmPasswordRequired: () => LocalizedString
			/**
			 * Passwords do not match
			 */
			confirmPasswordError: () => LocalizedString
			/**
			 * You have successfully registered. Please check your email to confirm your account.
			 */
			success: () => LocalizedString
			/**
			 * Click here to return to the login page
			 */
			successReturn: () => LocalizedString
		}
	}
}

export type Formatters = {}
