name: Run Lint, Tests and Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: https://www.test.com/
      NEXTAUTH_SECRET: test
      NEXTAUTH_URL: https://www.test.com/
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      VERCEL_ENV: preview
      SENDGRID_API_KEY: 123
      SENDGRID_FROM_EMAIL: test@test.com
      FORGOT_PASSWORD_JWT_SECRET: 123
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
