name: Github release

on:
  push:
    branches: [ main ]

jobs:
  github_release:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: https://www.test.com/
      NEXTAUTH_SECRET: test
      NEXTAUTH_URL: https://www.test.com/
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}